### ISSUE TITLE
Rule error (a typo)

### ISSUE THREAD

**Issue by Semmelbrot12** [Roblox-Developers/Guides#14]
![image](https://github.com/Roblox-Developers/Guides/assets/135644265/137d117e-29d4-44c3-ae1f-6c7855101599)
It's meant to say "an", not "and"

**Comment by WhoCutTheCheese** [comment]
https://github.com/Roblox-Developers/Guides/commit/6c4f459a192e7d5120520cdebbe53d8bb435cc02
Fixed typo
